# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:lts
        environment:
          DB_TEST_URI="mongodb://mongouser:mongopassword@localhost/dbtest?retryWrites=true&w=majority"
          SECRET='secret'
      - image: circleci/mongo
        environment:
          MONGO_INITDB_ROOT_USERNAME: mongouser
          MONGO_INITDB_ROOT_PASSWORD: p@mongopassword
    steps:
      - checkout
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.6.
      - run:
          name: Wait for db
          command: dockerize -wait mongodb://localhost:27017 -timeout 1m
      - run: npm i
      - run: npm test