# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:lts
        environment:
          DB_TEST_URI="mongodb://mongouser:mongopassword@localhost/dbtest?retryWrites=true&w=majority"
          SECRET='secret'
      - image: circleci/mongo
        environment:
          MONGO_INITDB_ROOT_USERNAME: mongouser
          MONGO_INITDB_ROOT_PASSWORD: p@mongopassword
    steps:
      - checkout
      - run: npm i
      - run: npm test