# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:lts
        environment:
          - DB_TEST_URI: mongodb://mongouser:mongopassword@localhost
          - SECRET: secret
      - image: circleci/mongo
        environment:
          - MONGO_INITDB_DATABASE=dbtest
          - MONGO_INITDB_ROOT_USERNAME: mongouser
          - MONGO_INITDB_ROOT_PASSWORD: mongopassword
    steps:
      - checkout
      - run:
          name: Waiting for Mongo
          command: dockerize -wait tcp://localhost:27017 -timeout 1m
      - run: npm i
      - run: npm test